# Generated by Django 5.2 on 2025-05-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_salaryrequest_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
