# Generated by Django 5.2 on 2025-05-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
