# Generated by Django 5.2 on 2025-05-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_emplo_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Emplo',
        ),
        migrations.DeleteModel(
            name='SalaryRequest',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
