# Generated by Django 5.2 on 2025-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_employee_email_attendance_salaryrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
